Repository Multiverse/Multiverse-NetherPortals, pull requests merged in 2024-08, with the labels that each got.

#267 Make end portal generation drop blocks and refactor code
  src/main/java/com/onarandombox/MultiverseNetherPortals/MultiverseNetherPortals.java
  src/main/java/com/onarandombox/MultiverseNetherPortals/listeners/MVNPEntityListener.java
  src/main/java/com/onarandombox/MultiverseNetherPortals/listeners/MVNPPlayerListener.java
  src/main/java/com/onarandombox/MultiverseNetherPortals/utils/EndPlatformCreator.java
Labels: release:minor

#262 ci: Fix dependency type for modrinth
  .github/workflows/call.platform_uploads.yml
Labels: no release

#269 Fix wrong destination for entity portal teleport
  src/main/java/com/onarandombox/MultiverseNetherPortals/listeners/MVNPEntityListener.java
Labels: release:patch
