Repository Multiverse/Multiverse-NetherPortals, pull requests merged in 2025-05, with the labels that each got.

#281 Trigger MV5 release build
  README.md
Labels: release:minor

#282 Fix @Service annotation
  src/main/java/org/mvplugins/multiverse/netherportals/MultiverseNetherPortals.java
  src/main/java/org/mvplugins/multiverse/netherportals/commands/LinkCommand.java
  src/main/java/org/mvplugins/multiverse/netherportals/commands/ListCommand.java
  src/main/java/org/mvplugins/multiverse/netherportals/commands/UnlinkCommand.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPCoreListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPEntityListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPlayerListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPluginListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/utils/EndPlatformCreator.java
  src/main/java/org/mvplugins/multiverse/netherportals/utils/MVEventRecord.java
  src/main/java/org/mvplugins/multiverse/netherportals/utils/MVLinkChecker.java
  src/main/java/org/mvplugins/multiverse/netherportals/utils/MVNameChecker.java
Labels: release:patch

#283 Fix @Contract annotation
  src/main/java/org/mvplugins/multiverse/netherportals/commands/NetherPortalsCommand.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPlayerListener.java
Labels: release:patch

#285 Use issue forms for repository
  .github/ISSUE_TEMPLATE/help.md
  .github/ISSUE_TEMPLATE/help.yml
  .github/ISSUE_TEMPLATE/report-a-bug.md
  .github/ISSUE_TEMPLATE/report-a-bug.yml
  .github/ISSUE_TEMPLATE/request-a-feature.md
  .github/ISSUE_TEMPLATE/request-a-feature.yml
Labels: no release

#286 Use EntityPortalReadyEvent to support handling portals on servers with disabled nether/end
  build.gradle
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPCoreListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPEntityListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPEntityPortalReadyListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPlayerListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPluginListener.java
Labels: release:patch

#287 Use our new dynamic listener api
  src/main/java/org/mvplugins/multiverse/netherportals/MultiverseNetherPortals.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPCoreListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPEntityListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPEntityPortalReadyListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPlayerListener.java
  src/main/java/org/mvplugins/multiverse/netherportals/listeners/MVNPPluginListener.java
Labels: release:patch
